-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 21, 2018 at 11:07 AM
-- Server version: 10.1.37-MariaDB
-- PHP Version: 7.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `final`
--
CREATE DATABASE IF NOT EXISTS `final` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_vietnamese_ci;
USE `final`;

-- --------------------------------------------------------

--
-- Table structure for table `article`
--

DROP TABLE IF EXISTS `article`;
CREATE TABLE `article` (
  `id` int(11) NOT NULL,
  `title` varchar(255) CHARACTER SET latin1 NOT NULL,
  `story` varchar(255) CHARACTER SET latin1 NOT NULL,
  `detail` varchar(255) CHARACTER SET latin1 NOT NULL,
  `image` varchar(255) CHARACTER SET latin1 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_vietnamese_ci;

--
-- Dumping data for table `article`
--

INSERT INTO `article` (`id`, `title`, `story`, `detail`, `image`) VALUES
(23, '<h1 class=\"art-title\">Australia: CÃ´ dÃ¢u sá»‘c náº·ng khi phÃ¡t hiá»‡n tÃ¬nh cÅ© lÃ  bá»‘ chá»“ng cá»§a mÃ¬nh</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/817/the-gioi-24h.html\">Tháº¿ giá»›i 24h</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><b>CÃ´ dÃ¢u Australia báº¥t ngá»</b><b>Â gáº·p láº¡i \"tÃ¬nh má»™t Ä‘Ãªm\" ngay trong lá»… cÆ°á»›i vÃ  báº¥t ngá» khi biáº¿t Ã´ng chÃ­nh lÃ  bá»‘ chá»“ng tÆ°Æ¡ng lai cá»§a mÃ¬nh. </b><b></b></p><table ', ''),
(21, '<h1 class=\"art-title\">BÃ¡o chÃ¢u Ã \"choÃ¡ng\" vÃ¬ HLV Park Hang-seo tháº³ng tay loáº¡i Anh Äá»©c, VÄƒn Quyáº¿t á»Ÿ Asian Cup 2019</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1042/asian-cup-2019.html\">Asian Cup 2019</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>BÃ¡o chÃ¢u Ã báº¥t ngá» trÆ°á»›c viá»‡c HLV Park Hang-seo khÃ´ng triá»‡u táº­p Anh Äá»©c, VÄƒn Quyáº¿t chuáº©n bá»‹ cho Asian Cup diá»…n ra vÃ o thÃ¡ng 1/2019.</strong></p><p style=\"text-ali', ''),
(22, '<h1 class=\"art-title\">Báº£ng giÃ¡ xe Ã´ tÃ´ Mercedes-Benz má»›i nháº¥t thÃ¡ng 12/2018: Maybach S 650 giÃ¡ 14,499 tá»· Ä‘á»“ng</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/971/bang-gia-o-to-moi-nhat.html\">Báº£ng giÃ¡ Ã´ tÃ´ má»›i nháº¥t</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Báº£ng giÃ¡ xe Ã´ tÃ´ Mercedes-Benz má»›i nháº¥t thÃ¡ng 12/2018 táº¡i thá»‹ trÆ°á»ng Viá»‡t Nam. Cáº­p nháº­t thÃ´ng tin giÃ¡ cÃ¡c máº«u xe Ã´ tÃ´ Mercedes-Benz thÃ¡ng 12/2018 nhanh vÃ  chÃ­nh', ''),
(19, '<h1 class=\"art-title\">Chuáº©n bá»‹ cho Asian Cup, HLV Park sáº½ trao cÆ¡ há»™i cho nhá»¯ng cáº§u thá»§ Ã­t Ä‘Æ°á»£c ra sÃ¢n </h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1042/asian-cup-2019.html\">Asian Cup 2019</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>â€œTráº£i qua 2 thÃ¡ng thi táº­p luyá»‡n vÃ  thi Ä‘áº¥u, nhiá»u cáº§u thá»§ Ä‘Ã£ quÃ¡ má»‡t má»i rá»“i. VÃ¬ váº­y tÃ´i sáº½ trao cÆ¡ há»™i cho nhá»¯ng cáº§u thá»§ Ã­t Ä‘Æ°á»£c ra sÃ¢n trong n', ''),
(24, '<h1 class=\"art-title\">Dá»± bÃ¡o thá»i tiáº¿t ngÃ y 17/12: HÃ  Ná»™i trá»i rÃ©t, Trung Bá»™ cÃ³ mÆ°a trÃªn diá»‡n rá»™ng</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/909/du-bao-thoi-tiet.html\">Dá»± bÃ¡o thá»i tiáº¿t</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>ÄÃªm nay vÃ  ngÃ y mai (17/12), do áº£nh hÆ°á»Ÿng cá»§a khÃ´ng khÃ­ láº¡nh tÄƒng cÆ°á»ng nÃªn cÃ¡c tá»‰nh tá»« Quáº£ng Trá»‹ Ä‘áº¿n Quáº£ng NgÃ£i cÃ³ mÆ°a vá»«a, cÃ³ nÆ¡i mÆ°a to.</strong></p', ''),
(7, '<h1 class=\"art-title\">HÃ© lá»™ 4 ngÃ´i sao Ä‘á»©ng sau thao tÃºng mÃ n ká»‹ch Ã©p MU sa tháº£i Mourinho</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1043/mu-chinh-thuc-sa-thai-mourinho.html\">MU chÃ­nh thá»©c sa tháº£i Mourinho</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><b>Theo tá» Daily Star hÃ© lá»™, 4 ngÃ´i sao Ä‘Ã£ Ä‘áº¿n gáº·p PhÃ³ Chá»§ tá»‹ch Ed Woodward vÃ  gÃ¢y sá»©c Ã©p buá»™c MU sa tháº£i Mourinho.</b></p><p style=\"text-align: justify;\">NhÃ³m nÃ y tuyÃªn b', ''),
(178, '<h1 class=\"art-title\">Káº¿t quáº£ xá»• sá»‘ BÃ¬nh DÆ°Æ¡ng hÃ´m nay 21/12/2018</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1010/ket-qua-xo-so-mien-nam.html\">Káº¿t quáº£ xá»• sá»‘ miá»n Nam</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Káº¿t quáº£ xá»• sá»‘ BÃ¬nh DÆ°Æ¡ng hÃ´m nay 21/12/2018. Cáº­p nháº­t káº¿t quáº£ xá»• sá»‘ miá»n Nam nhanh vÃ  chÃ­nh xÃ¡c nháº¥t trÃªn trang Äá»i sá»‘ng & <a href=\"http://www.doisongphaplu', '<p class=\"full_images\"><img style=\"max-width: 480px;border: none !important;\"  src=\"http://media.doisongphapluat.com/thumb_x500x/603/2018/12/21/xo-so-mien-nam-2112-anh-2.jpg\" alt=\"Káº¿t quáº£ xá»• sá»‘ BÃ¬nh DÆ°Æ¡ng hÃ´m nay 21/12/2018 - áº¢nh 1\" title=\"K'),
(176, '<h1 class=\"art-title\">Káº¿t quáº£ xá»• sá»‘ miá»n Báº¯c hÃ´m nay 21/12/2018</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1006/xo-so-mien-bac.html\">Xá»• sá»‘ miá»n Báº¯c </a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong><strong>Káº¿t quáº£ xá»• sá»‘ miá»n Báº¯c hÃ´m nay 21/12/2018. Cáº­p nháº­t káº¿t quáº£ xá»• sá»‘ miá»n Báº¯c nhanh vÃ  chÃ­nh xÃ¡c nháº¥t trÃªn trang Äá»i sá»‘ng & <a href=\"http://www.dois', '<p class=\"full_images\"><img style=\"max-width: 480px;border: none !important;\"  src=\"http://media.doisongphapluat.com/thumb_x500x/603/2018/12/21/xo-so-1.jpg\" alt=\"Káº¿t quáº£ xá»• sá»‘ miá»n Báº¯c hÃ´m nay 21/12/2018 - áº¢nh 1\" title=\"Káº¿t quáº£ xá»• sá»'),
(263, '<h1 class=\"art-title\">Káº¿t quáº£ xá»• sá»‘ miá»n Nam hÃ´m nay 21/12/2018</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1010/ket-qua-xo-so-mien-nam.html\">Káº¿t quáº£ xá»• sá»‘ miá»n Nam</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Káº¿t quáº£ xá»• sá»‘ miá»n Nam hÃ´m nay 21/12/2018. Cáº­p nháº­t káº¿t quáº£ xá»• sá»‘ miá»n Nam nhanh vÃ  chÃ­nh xÃ¡c nháº¥t trÃªn trang Äá»i sá»‘ng & <a href=\"http://www.doisongphapluat.', '<p class=\"full_images\"><img style=\"max-width: 480px;border: none !important;\"  src=\"http://media.doisongphapluat.com/thumb_x500x/603/2018/12/21/xo-so-mien-nam-2112-anh-2.jpg\" alt=\"Káº¿t quáº£ xá»• sá»‘ miá»n Nam hÃ´m nay 21/12/2018 - áº¢nh 1\" title=\"Káº¿'),
(177, '<h1 class=\"art-title\">Káº¿t quáº£ xá»• sá»‘ TrÃ  Vinh hÃ´m nay 21/12/2018</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1010/ket-qua-xo-so-mien-nam.html\">Káº¿t quáº£ xá»• sá»‘ miá»n Nam</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Káº¿t quáº£ xá»• sá»‘Â  TrÃ  Vinh hÃ´m nay 21/12/2018. Cáº­p nháº­t káº¿t quáº£ xá»• sá»‘Â  TrÃ  Vinh nhanh vÃ  chÃ­nh xÃ¡c nháº¥t trÃªn trang Äá»i sá»‘ng & <a href=\"http://www.doisongphaplua', '<p class=\"full_images\"><img style=\"max-width: 480px;border: none !important;\"  src=\"http://media.doisongphapluat.com/thumb_x500x/603/2018/12/21/xo-so-mien-nam-2112-anh-1.jpg\" alt=\"Káº¿t quáº£ xá»• sá»‘ TrÃ  Vinh hÃ´m nay 21/12/2018 - áº¢nh 1\" title=\"Káº¿t'),
(262, '<h1 class=\"art-title\">Káº¿t quáº£ xá»• sá»‘ VÄ©nh Long hÃ´m nay 21/12/2018</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1010/ket-qua-xo-so-mien-nam.html\">Káº¿t quáº£ xá»• sá»‘ miá»n Nam</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Káº¿t quáº£ xá»• sá»‘ VÄ©nh Long hÃ´m nay 21/12/2018. Cáº­p nháº­t káº¿t quáº£ xá»• sá»‘ VÄ©nh Long nhanh vÃ  chÃ­nh xÃ¡c nháº¥t trÃªn trang Äá»i sá»‘ng & <a href=\"http://www.doisongphapluat.', '<p class=\"full_images\"><img style=\"max-width: 480px;border: none !important;\"  src=\"http://media.doisongphapluat.com/thumb_x500x/603/2018/12/21/xo-so-mien-nam-2112-anh-3.jpg\" alt=\"Káº¿t quáº£ xá»• sá»‘ VÄ©nh Long hÃ´m nay 21/12/2018 - áº¢nh 1\" title=\"Káº¿'),
(1, '<h1 class=\"art-title\">LÃ½ do khÃ³ ngá» khiáº¿n hÃ ng loáº¡t nhÃ¢n viÃªn thÃº y nghá»‰ viá»‡c táº¡i TP.HCM</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/771/tin-tuc-thoi-su-24h.html\">Tin tá»©c thá»i sá»± 24h</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Viá»‡c gáº§n má»™t nÄƒm khÃ´ng Ä‘Æ°á»£c tráº£ lÆ°Æ¡ng Ä‘Ã£ khiáº¿n Ã­t nháº¥t 10 nhÃ¢n viÃªn thÃº y Ä‘á»‹a bÃ n thuá»™c chi cá»¥c ChÄƒn nuÃ´i vÃ  ThÃº y TP.HCM xin nghá»‰ viá»‡c. Tháº­m chÃ­, c', ''),
(3, '<h1 class=\"art-title\">MÃ³n ngon má»—i ngÃ y: Canh sÆ°á»n náº¥u dá»c mÃ¹ng cho bá»¯a cÆ¡m gia Ä‘Ã¬nh thÃªm ngon</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/825/mon-ngon-moi-ngay.html\">mÃ³n ngon má»—i ngÃ y</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Canh sÆ°á»n náº¥u dá»c mÃ¹ng cÃ³ vá»‹ chua chua ngá»t ngá»t hÃ²a quyá»‡n vá»›i nhau, cÃ¹ng mÃ u sáº¯c tÆ°Æ¡i mÃ¡t sáº½ giÃºp cáº£ nhÃ  xuÃ½t xoa mÃ£i khÃ´ng thÃ´i.</strong></p><table cellsp', ''),
(17, '<h1 class=\"art-title\">Náº¿u vÃ´ Ä‘á»‹ch Asian Cup 2019, Viá»‡t Nam sáº½ nháº­n thÆ°á»Ÿng 5 triá»‡u USD</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1042/asian-cup-2019.html\">Asian Cup 2019</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>So vá»›i tiá»n thÆ°á»Ÿng cho nhÃ  vÃ´ Ä‘á»‹ch AFF Cup 2018, má»©c thÆ°á»Ÿng náº¿u lÃªn ngÃ´i táº¡i CÃºp vÃ´ Ä‘á»‹ch bÃ³ng Ä‘Ã¡ chÃ¢u Ã - Asian Cup 2019 lá»›n hÆ¡n gáº¥p 20 láº§n.</strong></p>', ''),
(5, '<h1 class=\"art-title\">Qualcomm tiáº¿p tá»¥c â€œdáº±n máº·t TÃ¡o khuyáº¿t\" khi Ä‘áº¡t Ä‘Æ°á»£c lá»‡nh cáº¥m bÃ¡n iPhone táº¡i Äá»©c</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/812/kinh-doanh-online.html\">Kinh doanh Online</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Sau Trung Quá»‘c, cÃ¡c cá»­a hÃ ng Apple Store táº¡i Äá»©c Ä‘Ã£ pháº£i dá»«ng bÃ¡n nhá»¯ng chiáº¿c iPhone 7 vÃ  iPhone 8 vÃ¬ lá»‡nh cáº¥m má»›i.</strong></p><p style=\"text-align: justify;\">CÃ¡', ''),
(2, '<h1 class=\"art-title\">Sá»‘c vá»›i Ä‘Æ°á»ng dÃ¢y bÃ¡n bÃ o thai tá»« Nghá»‡ An sang Trung Quá»‘c</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/775/tin-phap-luat-moi-nhat-trong-ngay.html\">Tin phÃ¡p luáº­t má»›i nháº¥t trong ngÃ y</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Nhiá»u phá»¥ ná»¯ mang thai láº§n lÆ°á»£t xuáº¥t cáº£nh sang Trung Quá»‘c nhÆ°ng khi trá»Ÿ vá» thÃ¬ cÃ¡i thai trong bá»¥ng khÃ´ng cÃ²n...</strong><br /></p><table cellspacing=\"0\" cellpadding=', ''),
(13, '<h1 class=\"art-title\">TÃ i xáº¿ thoÃ¡t cháº¿t tháº§n ká»³ sau khi Ã´ tÃ´ bá»‹ cÃ¡n báº¹p dÃºm táº¡i dá»‘c cáº§u \"tá»­ tháº§n\" PhÃº Má»¹ </h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/761/tai-nan-giao-thong-moi-nhat.html\">Tai náº¡n giao thÃ´ng má»›i nháº¥t</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Sau cÃº va cháº¡m liÃªn hoÃ n, chiáº¿c xe Ã´ tÃ´ 4 chá»— bá»‹ Ä‘áº©y vá» phÃ­a trÆ°á»›c, lá»t vÃ o gáº§m container, biáº¿n dáº¡ng hoÃ n toÃ n. May máº¯n, nam tÃ i xáº¿ thoÃ¡t cháº¿t trong gan', ''),
(9, '<h1 class=\"art-title\">TÃ¬nh tiáº¿t rÃ¹ng mÃ¬nh vá»¥ tra táº¥n con ná»£ Ä‘áº¿n cháº¿t, vá»©t xÃ¡c ra quá»‘c lá»™ á»Ÿ Quáº£ng Ninh</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/775/tin-phap-luat-moi-nhat-trong-ngay.html\">Tin phÃ¡p luáº­t má»›i nháº¥t trong ngÃ y</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Sau khi con ná»£ tá»­ vong, Vinh cÃ¹ng Ä‘á»“ng bá»n Ä‘Ã£ giáº¥u xÃ¡c náº¡n nhÃ¢n, chá» Ä‘áº¿n ná»­a Ä‘Ãªm thÃ¬ mang xÃ¡c ra quá»‘c lá»™ 18A cÅ© (tá»‰nh Quáº£ng Ninh) vá»©t.</strong></p><p sty', ''),
(15, '<h1 class=\"art-title\">Thá»§ tÆ°á»›ng: Niá»m tin cá»§a ngÆ°á»i dÃ¢n vá»›i Äáº£ng, Ä‘áº¥t nÆ°á»›c vÃ  QuÃ¢n Ä‘á»™i ngÃ y cÃ ng Ä‘Æ°á»£c cá»§ng cá»‘</h1>', '<section class=\"story\">                                              <span>Sá»± kiá»‡n: </span>                                              <h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/912/tin-tuc-chinh-tri-xa-hoi.html\">Tin tá»©c ChÃ', '<div id=\"main-detail\">                                                                                                  <p style=\"text-align: justify;\"><strong>NhÃ¢n dá»‹p ká»· niá»‡m 74 nÄƒm NgÃ y thÃ nh láº­p QuÃ¢n Ä‘á»™i nhÃ¢n dÃ¢n Viá»‡t Nam, sÃ¡ng 21', ''),
(12, '<h1 class=\"art-title\">Thá»§y TiÃªn \"tÃ¡ há»a\" nghe máº¹ chá»“ng khÃ³c ná»©c ná»Ÿ há»i chuyá»‡n ly hÃ´n vá»›i CÃ´ng Vinh</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/433/thuy-tien.html\">Thá»§y TiÃªn</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Ná»¯ ca sÄ© Thá»§y TiÃªn vá»«a pháº£i lÃªn tiáº¿ng Ä‘Ã­nh chÃ­nh trÃªn trang cÃ¡ nhÃ¢n vá» tin Ä‘á»“n ly hÃ´n vá»›i CÃ´ng Vinh.</strong></p><p style=\"text-align: justify;\">CÃ´ng Vinh - Thá»§y ', ''),
(10, '<h1 class=\"art-title\">Tiáº¿p tá»¥c xÃ¢y dá»±ng QuÃ¢n Ä‘á»™i hÃ¹ng máº¡nh, báº£o vá»‡ vá»¯ng cháº¯c Tá»• quá»‘c Viá»‡t Nam XHCN</h1>', '<section class=\"story\">                                              <span>Sá»± kiá»‡n: </span>                                              <h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/912/tin-tuc-chinh-tri-xa-hoi.html\">Tin tá»©c ChÃ', '<div id=\"main-detail\">                                                                                                  <p style=\"text-align: justify;\"><strong>NhÃ¢n ká»· niá»‡m 74 nÄƒm ngÃ y thÃ nh láº­p QuÃ¢n Ä‘á»™i NhÃ¢n dÃ¢n Viá»‡t Nam (22/12/1944-22/', ''),
(16, '<h1 class=\"art-title\">Triá»u TiÃªn pháº£i bá»“i thÆ°á»ng cho gia Ä‘Ã¬nh sinh viÃªn Má»¹ tá»­ vong hÆ¡n 1 tá»‰ USD?</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/817/the-gioi-24h.html\">Tháº¿ giá»›i 24h</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Gia Ä‘Ã¬nh Otto Ä‘Ã²i Triá»u TiÃªn pháº£i bá»“i thÆ°á»ng 1 tá»‰ USD vÃ¬ Ä‘Ã£ ngÆ°á»£c Ä‘Ã£i vá» thá»ƒ xÃ¡c, gÃ¢y Ã¡p lá»±c lÃªn tinh tháº§n vÃ  lÃ m â€œcáº¡n kiá»‡tâ€ sá»©c khá»e con trai ', ''),
(20, '<h1 class=\"art-title\">Tuyá»ƒn Viá»‡t Nam há»™i quÃ¢n, sáºµn sÃ ng cho buá»•i táº­p Ä‘áº§u tiÃªn vÃ o ngÃ y mai (21/12)</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1042/asian-cup-2019.html\">Asian Cup 2019</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>HÃ´m nay (20/12), Ä‘á»™i tuyá»ƒn bÃ³ng Ä‘Ã¡ Viá»‡t Nam há»™i quÃ¢n táº¡i <a href=\"http://www.doisongphapluat.com/ha-noi.html\">HÃ  Ná»™i</a> Ä‘á»ƒ bÆ°á»›c vÃ o quÃ¡ trÃ¬nh chuáº©n bá»‹ cho Asian', ''),
(11, '<h1 class=\"art-title\">Vá»¥ sÃ¡t háº¡i ngÆ°á»i bÃ¡n cÃ¡ giá»¯a Ä‘á»“ng: PhÃ¡t hiá»‡n Ä‘iá»u báº¥t ngá» táº¡i nhÃ  nhÃ¢n chá»©ng Ä‘i cÃ¹ng</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/775/tin-phap-luat-moi-nhat-trong-ngay.html\">Tin phÃ¡p luáº­t má»›i nháº¥t trong ngÃ y</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>LiÃªn quan Ä‘áº¿n vá»¥ ngÆ°á»i phá»¥ ná»¯ bÃ¡n cÃ¡ bá»‹ sÃ¡t háº¡i giá»¯a Ä‘á»“ng lÃºc ráº¡ng sÃ¡ng. quÃ¡ trÃ¬nh thu tháº­p tÃ i liá»‡u, chá»©ng cá»©, cÆ¡ quan chá»©c nÄƒng Ä‘Ã£ niÃªm phong má', ''),
(6, '<h1 class=\"art-title\">Vá»«a nghá»‰ viá»‡c má»™t tuáº§n, cá»±u thÆ° kÃ½ tÃ²a Ã¡n Ä‘Ã£ xÃ´ng Ä‘áº¿n Ä‘Ã¡nh luáº­t sÆ° ngay trÆ°á»›c phÃ²ng xÃ©t xá»­</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/774/tin-tuc-phap-luat.html\">Tin tá»©c phÃ¡p luáº­t </a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>TrÆ°á»›c giá» xÃ©t xá»­, má»™t nam luáº­t sÆ° báº¥t ngá» bá»‹ cá»±u thÆ° kÃ½ tÃ²a Ã¡n xÃ´ng Ä‘áº¿n Ä‘áº¥m tháº³ng vÃ o máº·t trÆ°á»›c sá»± chá»©ng kiáº¿n cá»§a nhiá»u ngÆ°á»i.Â </strong></p', ''),
(8, '<h1 class=\"art-title\">Video: 2 Ä‘á»©a tráº» trá»™m Ã´tÃ´, lÃ¡i xe bá» cháº¡y hÃ ng chá»¥c km rá»“i gÃ¢y tai náº¡n</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/775/tin-phap-luat-moi-nhat-trong-ngay.html\">Tin phÃ¡p luáº­t má»›i nháº¥t trong ngÃ y</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Sau khi Ä‘á»™t nháº­p vÃ o nhÃ  ngÆ°á»i dÃ¢n, bá»™ Ä‘Ã´i tháº¥y Ã´ tÃ´ táº£i cáº¯m sáºµn chÃ¬a khÃ³a nÃªn leo lÃªn lÃ¡i Ä‘i. Bá» cháº¡y Ä‘Æ°á»£c 15 km thÃ¬ tÃ´ng vÃ o báº£ng hiá»‡u giao thÃ´n', ''),
(4, '<h1 class=\"art-title\">Video: CÃ´ng PhÆ°á»£ng ná»•i nháº¥t buá»•i táº­p Ä‘áº§u tiÃªn cho Asian Cup vÃ¬ kiá»ƒu tÃ³c \"sÃºp lÆ¡\"</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/1050/tien-toi-asian-cup-2019.html\">Tiáº¿n tá»›i Asian Cup 2019</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>CÃ´ng PhÆ°á»£ng, VÄƒn ToÃ n Ä‘á»u Ä‘Ã£ thay Ä‘á»•i nhá»¯ng kiá»ƒu tÃ³c ná»•i báº­t trÆ°á»›c khi ÄT Viá»‡t Nam há»™i quÃ¢n chuáº©n bá»‹ cho Asian Cup 2019.</strong></p><p style=\"text-align: ju', ''),
(18, '<h1 class=\"art-title\">Xe bá»“n chá»Ÿ xÄƒng phÃ¡t ná»• táº¡i Ä‘Ã¨o Háº£i VÃ¢n, tÃ i xáº¿ tá»­ vong</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/974/tin-tuc-tai-nan-giao-thong-moi-nhat.html\">Tin tá»©c tai náº¡n giao thÃ´ng má»›i nháº¥t</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Xe bá»“n chá»Ÿ xÄƒng lao xuá»‘ng vá»±c rá»“i phÃ¡t ná»• khiáº¿n tÃ i xáº¿ tá»­ vong trong xe, cÃ²n phá»¥ xe má»Ÿ cá»­a nháº£y ra ngoÃ i nÃªn chá»‰ bá»‹ thÆ°Æ¡ng.</strong></p><p style=\"text-alig', ''),
(14, '<h1 class=\"art-title\">Äi lá»… chÃ¹a, bÃ ng hoÃ ng phÃ¡t hiá»‡n thi thá»ƒ bÃ© gÃ¡i sÆ¡ sinh trong tÃºi nilon</h1>', '<section class=\"story\"><span>Sá»± kiá»‡n: </span><h3 class=\"title\"><a href=\"http://www.doisongphapluat.com/su-kien/771/tin-tuc-thoi-su-24h.html\">Tin tá»©c thá»i sá»± 24h</a> <span class=\"arrow-3\"></span></h3></section>', '<div id=\"main-detail\"><p style=\"text-align: justify;\"><strong>Trong lÃºc Ä‘i lá»… chÃ¹a, má»™t ngÆ°á»i phá»¥ ná»¯ á»Ÿ HÃ  TÄ©nh Ä‘Ã£ tÃ¡ há»a khi phÃ¡t hiá»‡n thi thá»ƒ bÃ© gÃ¡i sÆ¡ sinh Ä‘á»±ng trong tÃºi nilon.</strong></p><p style=\"text-align: justif', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `detail` (`detail`),
  ADD UNIQUE KEY `title` (`title`,`story`,`detail`,`image`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `article`
--
ALTER TABLE `article`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=403;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
